DROP TABLE IF EXISTS PHONES
DROP TABLE IF EXISTS USERS

DROP SEQUENCE IF EXISTS PHONES_SEQ

CREATE SEQUENCE PHONES_SEQ START WITH 1 INCREMENT BY 1

CREATE TABLE USERS (ID VARCHAR(200) PRIMARY KEY, NAME VARCHAR(200), EMAIL VARCHAR(100), PWD VARCHAR(100), CREATED TIMESTAMP, LAST_UPDATE TIMESTAMP, LAST_LOGIN TIMESTAMP, TOKEN VARCHAR(200), ACTIVE BOOLEAN)
CREATE TABLE PHONES (ID INTEGER DEFAULT PHONES_SEQ.NEXTVAL PRIMARY KEY, PHONE_NUMBER VARCHAR(40), CITY_CODE VARCHAR(40), COUNTRY_CODE VARCHAR(40), USER_ID INTEGER)
